### ISSUE TITLE
Add BusStop timestamps

### ISSUE THREAD

**Issue by dfaulken** [umts/stop-project#10]
@sherson suggested that default timestamps would be useful here. I didn't think they were needed originally.

**Comment by dfaulken** [comment]
@sherson, do I recall that you also recommended a specific `completed_at` timestamp, and retroactively setting all UMTS stops which our service managers confirm to have a timestamp of 'right now'?

**Comment by sherson** [comment]
Yes please

**Comment by dfaulken** [comment]
OK, so first we'll need that list.

**Comment by dfaulken** [comment]
Received the list yesterday, but it also turns out that service managers haven't entered anything into the app yet, so I can just create empty timestamps. I'll work on this now.
