### ISSUE TITLE
Use GTFS export for routes

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#101]
@dfaulken is investigating some issues with the current export (#97 #98). I mentioned to him that another approach possibly worth considering is using the GTFS export:

- PVTA's current file: http://www.pvta.com/g_trans/ 
- Archive: https://transitfeeds.com/p/massdot/104
- Specs: https://developers.google.com/transit/gtfs/reference/

We would need to confirm with SATCo and VATCo which dates the feed files need to cover in order to include all the routes.

The upside being that we would not have to create/troubleshoot/maintain our own control file.

**Comment by dfaulken** [comment]
Should we get a data sample now so we can start development, in anticipation of this being the path forward? Or should we wait until we have approval from VATCo/SATCo/PVTA?

**Comment by sherson** [comment]
We don't need approval from VATCo/SATCo/PVTA for this; it's up to us (I'm positive they won't object to using an already produced/supported/hosted source). 

To me it's appealing since (along with not having to create/troubleshoot/maintain our own control file) we're already familiar with GTFS for other things anyway, but I don't feel strongly about it. Do you have any opinion? 

Based on the contents of `calendar.txt` and `calendar_dates.txt`, the [2018-05-01](https://transitfeeds.com/p/massdot/104/20180501) file looks good (assuming the date range of 5/6-12 is in fact good, which is what we were told).

**Comment by sherson** [comment]
So to answer your question a bit more directly, I think we should develop this, unless anyone has any objections.

**Comment by dfaulken** [comment]
@mboneil should we roll into the open PR's rake task, or address the algorithm separately before taking on a new data source?

**Comment by mboneil10** [comment]
Oh sorry @dfaulken I didn't see this comment four days ago.

**Comment by mboneil10** [comment]
I think since we should address the algorithm separately before taking on a new data source. That's just my impression, in order to keep changes as clear as possible. What do you think @dfaulken?

**Comment by Anbranin** [comment]
@sherson wants me to work on this unless someone else wants to tackle it. I'm going to wait until you all address whatever problems you were having with the algorithm, though. 
Or perhaps I can at least start it. Let me know. I'd prefer someone else assign me to the issue, however. I'm available when you need me after I finish up a couple things today.
