### ISSUE TITLE
Order by route displaying both directions as same stops

### ISSUE THREAD

**Issue by jforgue** [umts/stop-project#108]
Order stops by route is displaying almost the same stops in the same order for both directions.

<img width="901" alt="screen shot 2018-07-13 at 10 56 07 am" src="https://user-images.githubusercontent.com/26842354/42698300-7bb531ce-868b-11e8-862e-b983580e61e1.png">

**Comment by dfaulken** [comment]
Well in order to diagnose this, we need to see what I assume is the seed data that led to it, since this is from development.

**Comment by jforgue** [comment]
Yes, I believe this is a seed issue. I'll close when I'm certain.
