### ISSUE TITLE
Order by status is showing duplicates

### ISSUE THREAD

**Issue by jforgue** [umts/stop-project#109]
Order by status is showing duplicates for both pending and completed stops.

<img width="367" alt="screen shot 2018-07-13 at 10 56 33 am" src="https://user-images.githubusercontent.com/26842354/42698377-ba0e6666-868b-11e8-946e-6bda8a2eafbd.png">

**Comment by mboneil10** [comment]
How did you produce this bug and #108 ?

**Comment by jforgue** [comment]
I completed a stop and updated a stop in the view.

**Comment by mboneil10** [comment]
AH
