### ISSUE TITLE
First and last stops (on a trip) list routes twice

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#120]
For example, [Sugarloaf Estates](https://stop-project.admin.umass.edu/bus_stops/9/edit) and [The Boulders](https://stop-project.admin.umass.edu/bus_stops/157/edit) show:

Routes | 31, 31
-- | --

[Stop and Shop](https://stop-project.admin.umass.edu/bus_stops/127/edit) and [Mill Hollow](https://stop-project.admin.umass.edu/bus_stops/21/edit) show:

Routes | 33, 33
-- | --

Not really a problem, but a bit odd. Is this worth correcting?

**Comment by dfaulken** [comment]
> Is this worth correcting?

Yes. The table should be indexed to prevent this moving forward as well.

**Comment by dfaulken** [comment]
Sorry, I read this too quickly before. This isn't a table index problem. Trip endpoints will occur once in each direction.

This is just a view issue.

However we should also (separately) index the table to prevent duplicates.
