### ISSUE TITLE
Routes missing stops

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#121]
@mboneil10 provided a list of routes without stops according to:

`Route.includes(:bus_stops).where(bus_stops: {id: nil}).pluck(:number).uniq`

> "10s", "NE", "OWL", "P20E", "P21E", "PV", "T1", "T2", "T20", "T21", "T23", "T24", "T3", "T4", "T5", "T92", "WS"

Confirmed that P21E does not have any stops associated with it in the app (through the UI). Looked at archived GTFS file (that was used for the last import):

https://transitfeeds.com/p/massdot/104/20180501

routes.txt has:

```
921,P21E
```

trips.txt has:

```
921,S1803-AMD-Weekday-53,2609250-S1803-AMD-Weekday-53 
```

stop_times.txt has:

```
2609250-S1803-AMD-Weekday-53,06:27:31,06:27:31,387
```

This indicates that stop 387 should be associated with P21E. Any thoughts as to why it’s not?

Related notes:

* Stop 387 is on P21E in Avail and at [maps.google.com](https://goo.gl/maps/sZMF66ebbgw) (based on the current GTFS file). 
* I’m not sure if this actually matters, but calendar.txt does have that service_id defined:

```
S1803-AMD-Weekday-53,1,1,1,1,1,0,0,20180622,20180622
```

**Comment by mboneil10** [comment]
I'll shorten the corresponding files to only those lines, put a binding in, and run the rake task.

**Comment by mboneil10** [comment]
I actually can't find that line in `stop_times.txt`

**Comment by sherson** [comment]
I downloaded the file from https://transitfeeds.com/p/massdot/104/20180501 again to confirm. The example I mentioned is from line `121458`:

![gtfs screencap](https://user-images.githubusercontent.com/409008/43783122-ed7504ae-9a2e-11e8-8eec-2a3eadfe80a1.png)
