### ISSUE TITLE
Searching by stop name when not unique

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#122]
PVTA stop names are not always unique (there are many duplicates and some triplicates). Currently, searching by stop name (rather than stop ID) always returns the first stop name on the list. For example, choosing the name for one of these...

name | id
--|--
Plumtree / Mayflower | 1590
Plumtree / Mayflower | 1596
Plumtree / Mayflower | 1607

...always returns 1590.

The best solution is for PVTA to use unique names... we'll ask them if that's planned.

**Comment by dfaulken** [comment]
In other cases, don't we show the name as `Plumtree / Mayflower (1590)`, for example? So that at least there are as many autocompleted names as DB entires?

Potential short-term fix.

**Comment by sherson** [comment]
Yes, we should list the stop number in parenthesis after the stop name (I can't think of a reason not to do that everywhere).
