### ISSUE TITLE
Stops missing routes

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#123]
@mboneil10 provided this list of stops without a route:  

`BusStop.includes(:routes).where(routes: {id: nil}).pluck(:hastus_id).uniq`

> "5070", "6039", "5048", "9016", "T_1002", "5031", "9020", "9121", "6301", "1497", "1485", "6025", "1493", "1491", "1626", "1634", "1638", "1645", "1647", "9172", "813", "6405", "7484", "5050", "5049", "212", "213", "216", "218", "215", "214", "10002", "6378", "1108", "6131", "6132", "6133", "1045", "1048", "1059", "951", "6033", "281", "6287", "9200", "401", "9015", "1931", "625", "745", "837", "1368", "1373", "1349", "1243", "1248", "1294", "1313", "1459", "1469", "1342", "1295", "1482", "1490", "1420", "6253", "6257", "5072", "6252", "7444", "7443", "1090", "1118", "340", "1864", "9906", "9905", "717", "743", "1094", "1123", "1180", "6311", "793", "853", "6312", "6309", "6314", "810", "836", "980", "6310", "6284", "754", "6315", "741", "787", "6313", "762", "9314", "9325", "677", "1531", "1549", "1551", "1538", "1575", "5077", "6449", "10102", "9080", "11004", "9043", "10010", "9046", "10009", "9042", "807", "6889", "10000", "9124", "9122", "9128", "9114", "9123", "9134", "9204", "9113", "9116", "10001", "9125", "9126", "9111", "9203", "9135", "9127", "9118", "9115", "9119", "9112", "9117", "6038", "6113", "6112", "628", "9154", "5346", "1869", "9251", "1872", "6372", "6268", "783", "777", "6269", "122", "11130", "1997", "6259", "9079", "11008", "877", "878", "880", "882", "5039", "734", "1781", "9319", "758", "5017", "652", "772", "785", "658", "744", "9068", "9045", "9164", "9163", "9182", "9181", "1848", "963", "6275", "6276", "392", "405", "299", "1293", "1289", "9069", "831", "839", "821", "822", "808", "9167", "366", "480", "5069", "1250", "1202", "1173", "1169", "1231", "1229", "1196", "325", "6355", "1731", "1150", "9898", "385", "9440", "11114", "5005", "5006", "5007", "5009", "5008", "9104", "9100", "9102", "11113", "632", "644", "606", "9292", "9171", "9169", "5345", "188", "5067", "1517", "1527", "1535", "6855", "11123", "5962", "6502", "5075", "6126", "6127", "589", "592", "9165", "4370", "4371", "11005", "9044", "9183", "9091", "9035", "9061", "9033", "9030", "458", "671", "655", "657", "9810", "6426", "1865", "9899", "496", "347", "6809", "6258", "6251", "6250", "1434", "9018", "348", "5052", "5051", "622", "5068", "9001", "9013", "6408", "6409", "6418", "389", "1217", "6134", "6138", "6277", "9904", "9085", "9084", "9184", "9083", "1881", "1895", "1891", "9131", "9048", "6456", "11121", "9017", "9082", "1855", "667", "6135", "6279", "5029", "6412", "1817", "1860", "6423", "1840", "6136", "6324", "5065", "6280", "514", "1835", "5064", "1828", "1830", "1055", "536", "540", "327", "9144", "6245", "9143", "5066", "9205", "5028", "6888", "205", "6261", "1592", "9133", "9191", "6451", "6455", "6254", "1598", "289", "10005", "5800", "649", "3", "27", "5046", "5045", "5078", "5047", "1794", "6810", "6137", "6274", "1082", "1085", "1122", "1163", "1138", "710", "4182", "9162", "9170", "11125", "285", "9009", "9180", "9190", "10003", "11000", "11001", "11002", "11006", "11009", "11010", "11120", "6472", "9192", "9992", "11141", "11144", "9991", "11007", "11145", "11142", "10004", "11112.", "1116", "1074", "1164", "149", "6260", "7000", "48", "6265", "6273", "6911", "6320", "928", "6318", "865", "884", "6319", "900", "6316", "6317", "6321", "952", "6283", "633", "6110", "6278", "298", "309", "310", "311", "312", "301", "1348", "1337", "1430", "1370", "1384", "342", "1629", "6256", "6255", "343", "6271", "6272", "6264", "253", "1541", "6249", "1533", "1536", "1525", "1526", "1572", "1574", "1364", "1468", "1550", "1553", "1460", "1462", "1510", "1569", "1305", "1590", "1596", "1607", "1471", "1472", "1473", "1556", "1558", "1637", "1639", "1583", "1212", "1564", "1262", "1397", "1410", "1523", "1568", "1563", "6443", "1102", "1111", "1087", "1088", "1095", "1098", "1874", "6015", "1034", "5088", "4171", "6460", "6459", "6461", "643", "515", "9094", "763", "9073", "9076", "5085", "7043", "6141", "1866", "1010", "857", "1165", "1175", "6323", "912", "945", "1057", "1060", "820", "1256", "1272", "1071", "987", "988", "1016", "1092", "1303", "1308", "895", "6322", "1227", "1241", "1099", "1124", "4540", "4541", "1333", "1344", "400", "409", "396", "6503", "403", "420", "395", "7006", "1823", "305", "9206", "9155", "5016", "1171", "1155", "1159", "1172", "1170", "11111", "5900", "T_1000", "1868", "1870", "9101", "5082", "5083", "5084", "9103", "9092", "487", "2472", "2473", "959", "5034", "1047", "1072", "1450", "9090", "9010", "T_1003", "1324", "1318", "9060", "9041", "9132", "9047", "9081", "9027", "9031", "9025", "9105", "9108", "9321", "9313", "344", "5011", "5012", "334", "9317", "9318", "407", "6419", "6417", "862", "834", "815", "816", "804", "780", "782", "9107", "279", "570", "1096", "1141", "1191", "1312", "1389", "660", "801", "824", "997", "1888", "6424", "6425", "5", "6370", "8009", "T_1001", "1519", "429", "1923", "602", "1822", "1836", "1854", "1843", "1839", "1827", "9093", "1435", "1394", "5030", "88", "408", "7005", "5347", "6462", "8001", "6267", "5344", "5343", "5090", "5089", "6187", "6188", "352", "769", "7004", "1885", "6286", "6111", "321", "6140", "6890", "833", "627", "7002", "8023", "379", "5086", "5010", "6422", "9145", "5014", "5015", "5013", "9120", "9029", "9036", "9034", "9026", "9028", "9023", "5076", "5056", "6954", "9062", "9024", "532", "9032", "1861", "1489", "9106", "9109", "9110", "9004", "9003", "349", "326", "275", "5087", "672", "7007", "6109", "6114", "1218", "1223", "1146", "1148", "6910", "1245", "1251", "1182", "1190"

Some of them are no longer in use. In fact, those are named:

> This stop is no longer in use

But we're not sure about the others. We need to determine if any of those stops are current. If so, why are they not associated with any routes? 

Related to #121

**Comment by mboneil10** [comment]
To add to names for those no longer in use, here's an "improved" query of the one above:
```
BusStop.includes(:routes).where(routes: {id: nil}).where("name not like '%This stop is no longer in use%' and name not like '%NOT A REAL STOP%' and name not like '%Stop no longer used%' and name not like '%No longer serviced%' and name not like '%NOT A STOP%' and name not like '%not real bus stop%' and name not like '%Discontinued%' and name not like '%This stop is no longer used%'").pluck(:hastus_id)
```

> ["5070", "6039", "5048", "9016", "T_1002", "5031", "9020", "9121", "6301", "1497", "1485", "6025", "1493", "1491", "1626", "1634", "1638", "1645", "1647", "9172", "813", "6405", "7484", "5050", "5049", "212", "213", "216", "218", "215", "214", "10002", "6378", "1108", "6131", "6132", "6133", "1045", "1048", "1059", "951", "6033", "281", "6287", "9200", "401", "9015", "1931", "625", "745", "837", "1368", "1373", "1349", "1243", "1248", "1294", "1313", "1459", "1469", "1342", "1295", "1482", "1490", "1420", "6253", "6257", "5072", "6252", "1090", "1118", "340", "1864", "9906", "9905", "717", "743", "1094", "1123", "1180", "6311", "793", "853", "6312", "6309", "6314", "810", "836", "980", "6310", "6284", "754", "6315", "741", "787", "6313", "762", "9314", "9325", "677", "1531", "1549", "1551", "1538", "1575", "5077", "6449", "10102", "9080", "11004", "9043", "10010", "9046", "10009", "9042", "807", "6889", "10000", "9124", "9122", "9128", "9114", "9123", "9134", "9204", "9113", "9116", "10001", "9125", "9126", "9111", "9203", "9135", "9127", "9118", "9115", "9119", "9112", "9117", "6038", "6113", "6112", "628", "9154", "5346", "9251", "6372", "6268", "783", "777", "6269", "122", "11130", "1997", "6259", "9079", "11008", "877", "878", "880", "882", "5039", "734", "1781", "9319", "758", "5017", "652", "772", "785", "658", "744", "9068", "9045", "9164", "9163", "9182", "9181", "1848", "963", "6275", "6276", "392", "405", "299", "1293", "1289", "9069", "831", "839", "821", "822", "808", "366", "480", "5069", "1250", "1202", "1173", "1169", "1231", "1229", "1196", "325", "1731", "1150", "385", "11114", "5005", "5006", "5007", "5009", "5008", "9104", "9100", "9102", "11113", "632", "644", "606", "9292", "9171", "9169", "5345", "188", "5067", "1517", "1527", "1535", "6855", "11123", "5962", "6502", "5075", "6126", "6127", "589", "592", "9165", "4370", "4371", "11005", "9044", "9183", "9091", "9035", "9061", "9033", "9030", "458", "671", "655", "657", "9810", "6426", "496", "347", "6809", "6258", "6251", "6250", "1434", "9018", "348", "5052", "5051", "622", "5068", "9001", "9013", "6408", "6409", "6418", "389", "1217", "6134", "6138", "6277", "9904", "9085", "9084", "9184", "9083", "1881", "1895", "1891", "9131", "9048", "6456", "11121", "9017", "9082", "1855", "667", "6135", "6279", "5029", "6412", "1817", "1860", "6423", "1840", "6136", "6324", "5065", "6280", "514", "1835", "5064", "1828", "1830", "1055", "536", "540", "327", "9144", "6245", "9143", "5066", "9205", "5028", "6888", "205", "6261", "1592", "9133", "9191", "6451", "6455", "6254", "1598", "289", "10005", "5800", "649", "3", "27", "5046", "5045", "5078", "5047", "1794", "6810", "6137", "6274", "1082", "1085", "1122", "1163", "1138", "710", "4182", "9162", "9170", "11125", "285", "9009", "9180", "1116", "1074", "1164", "149", "6260", "7000", "48", "6265", "6273", "6911", "6320", "928", "6318", "865", "884", "6319", "900", "6316", "6317", "6321", "952", "6283", "633", "6110", "6278", "298", "309", "310", "311", "312", "301", "1348", "1337", "1430", "1370", "1384", "342", "1629", "6256", "6255", "343", "6271", "6272", "6264", "253", "1541", "6249", "1533", "1536", "1525", "1526", "1572", "1574", "1364", "1468", "1550", "1553", "1460", "1462", "1510", "1569", "1305", "1590", "1596", "1607", "1471", "1472", "1473", "1556", "1558", "1637", "1639", "1583", "1212", "1564", "1262", "1397", "1410", "1523", "1568", "1563", "6443", "1102", "1111", "1087", "1088", "1095", "1098", "1874", "6015", "1034", "5088", "4171", "6460", "6459", "6461", "643", "515", "9094", "763", "9073", "9076", "5085", "7043", "6141", "1010", "857", "1165", "1175", "6323", "912", "945", "1057", "1060", "820", "1256", "1272", "1071", "987", "988", "1016", "1092", "1303", "1308", "895", "6322", "1227", "1241", "1099", "1124", "4540", "4541", "1333", "1344", "400", "409", "396", "6503", "403", "420", "395", "7006", "1823", "305", "9206", "9155", "5016", "1171", "1155", "1159", "1172", "1170", "11111", "5900", "T_1000", "1868", "1870", "9101", "5082", "5083", "5084", "9103", "9092", "487", "2472", "2473", "959", "5034", "1047", "1072", "1450", "9090", "9010", "T_1003", "1324", "1318", "9060", "9041", "9132", "9047", "9081", "9027", "9031", "9025", "9105", "9108", "9321", "9313", "344", "5011", "5012", "334", "9317", "9318", "407", "6419", "6417", "862", "834", "815", "816", "804", "780", "782", "9107", "279", "570", "1888", "6424", "6425", "5", "6370", "8009", "T_1001", "1519", "602", "1822", "1836", "1854", "1843", "1839", "1827", "9093", "1435", "1394", "5030", "88", "408", "7005", "5347", "6462", "8001", "6267", "5344", "5343", "5090", "5089", "6187", "6188", "352", "769", "7004", "1885", "6286", "6111", "321", "6140", "6890", "833", "627", "7002", "8023", "379", "5086", "5010", "6422", "9145", "5014", "5015", "5013", "9120", "9029", "9036", "9034", "9026", "9028", "9023", "5076", "5056", "6954", "9062", "9024", "532", "9032", "1861", "1489", "9106", "9109", "9110", "9004", "9003", "349", "326", "275", "5087", "672", "7007", "6109", "6114", "1218", "1223", "1146", "1148", "6910", "1245", "1251", "1182", "1190"]

**Comment by mboneil10** [comment]
Going to ask all involved with the project if this is preferred or not. For example, it could be that a stop is not being used (without a route) but still needs to be serviced.

**Comment by mboneil10** [comment]
Also, related #129
