### ISSUE TITLE
Should we use &. or try?

### ISSUE THREAD

**Issue by dfaulken** [umts/stop-project#127]
This line was introduced (and merged rather quickly) in #126:

https://github.com/umts/stop-project/blob/5d91631127a8dd9efb79e25c5bf2ce6d48ec966e/app/models/bus_stop.rb#L234

I think we should decide as a team, at least for this project if not overall, whether we favor this (from Ruby) or `try` (from Rails), so that we can adopt a consistent approach, rather than mixing the two.

**Comment by dfaulken** [comment]
> As for the "merged rather quickly," @sherson told me to. Not ideal, but Krystal needed the CSV.

OK, no problem since there was an operational reason. In future, best to document, just for traceability's sake (particularly on PVTA projects which have multiple stakeholder groups).

**Comment by Anbranin** [comment]
Oh, okay, do you think a comment on the PR would have been sufficient? (I should have at _least_ done that)

**Comment by dfaulken** [comment]
Either is fine, I think. Thanks for documenting in both places.

**Comment by mboneil10** [comment]
I'd rather we change the whole site to have `try`. 

There's no reason to use strange characters when `try` isn't a long word and makes more sense in terms of readability.  It is valid ruby, but that doesn't mean it's the best thing to use for rails.

Ultimately, think we're making this a bigger deal than it needs to be. We'll use 'try' throughout. I'll make the changes necessary.
