### ISSUE TITLE
Delete non-public stops

### ISSUE THREAD

**Issue by mboneil10** [umts/stop-project#129]
Cleanup after https://github.com/umts/stop-project/issues/98.

**Comment by mboneil10** [comment]
Ok, went through a plan for this with @dfaulken. I'll run the export and delete any stops that are in production but not in the export. So, I'll be doing this through the rails console. I expect to write the command below/somewhere public first before running.

**Comment by dfaulken** [comment]
@mboneil10 did you need a hand with this one?

**Comment by dfaulken** [comment]
@mboneil10 were you able to perform this, or is this still pending?

**Comment by dfaulken** [comment]
Still unclear whether this was performed.
