### ISSUE TITLE
Export Data to Hastus

### ISSUE THREAD

**Issue by mboneil10** [umts/stop-project#138]
Either an XML or OIG

**Comment by mboneil10** [comment]
Talked with @dfaulken about how to achieve this a week ago. @sherson and I are waiting to hear back from Laurel.

**Comment by sherson** [comment]
Who has thumbs and forgot to hit send when emailing Laurel? This guy.

I emailed her today.

**Comment by dfaulken** [comment]
Question: what are we waiting on Laurel for?

**Comment by dfaulken** [comment]
@sherson any updates here? I can develop a batch XML export as soon as we know what it needs to look like.

**Comment by sherson** [comment]
No, but I'll reach out to PVTA.

**Comment by sherson** [comment]
PVTA got stuck when they hit the limit of the number of custom attributes in Hastus. They recently got past that hurdle and imported using the CSV (though they want to make more attributes for the purposes of validation). 

I've reached out to them to clarify what they want for a workflow.

**Comment by werebus** [comment]
As @sherson mentioned in the above comment, it seems as if the CSV export is sufficient.
