### ISSUE TITLE
Rake or something task for stop data CSV output

### ISSUE THREAD

**Issue by Anbranin** [umts/stop-project#14]
I keep getting asked for a spreadsheet of all the stop data for UMTS routes (and sometimes other routes), so I made a script for it. I go into the console and run the commands to get the data. This happens enough, however, to warrant a page where the user can select the data they want about each stop and print it out to a page, or at the very least a rake task so I can run ONE command from a preloaded rails environment and not have to go through all the commands to find the stops I want and `uniq` them every time.

**Comment by Anbranin** [comment]
Or look at where they're using a paper binder. 😛 
But yeah, no, that is my first choice.

**Comment by dfaulken** [comment]
So, what are those commands that you have run? And what are the data that people have asked for? This is related to PVTA, so I'm happy to whip something up.

**Comment by Anbranin** [comment]
I've had people here and at SATCO ask for this. Here's the file I use, half of it is notes to myself for what to type in the command line, and half is a script...

``` ruby
# To get all transit stops:
# transit_routes = Route.where(number: [list of transit numbers])
# transit_stops = []
# transit_routes.each do |route|
# transit_stops << route.bus_stops
# end
# transit_stops = transit_stops.flatten
# transit_stops.uniq!
def parse_stops(stops)
  attributes = %w(
        id name updated_at completed? accessible bench curb_cut lighting mounting mounting_direction schedule_holder shelter sidewalk sign trash
        bolt_on_base bus_pull_out_exists? extend_pole? has_power? new_anchor? new_pole? solar_lighting? straighten_pole? system_map_exists?
        mounting_clearance_after mounting_clearance_before created_at updated_at completed? completed_at
  )
  headers = attributes.map(&:humanize)
  CSV.open('stop_data.csv', 'wb') do |csv|
    csv << headers
    stops.each do |stop|
      row = []
      attributes.each do |attribute|
        row << stop.send(attribute).to_s || "No Data Available"
      end
      csv << row
    end
  end
end
```

**Comment by Anbranin** [comment]
It's not super flexible and I realize that, but I just change it based upon what I'm being asked to do in the moment.

**Comment by dfaulken** [comment]
Okay, so literally a listing of every attribute? Can do.

Do we think we prefer a rake task, a downloadable CSV, a view with a table, or some combination of those three?

**Comment by Anbranin** [comment]
Add to those attributes the route number as well--that was requested recently by the service manager.
I think a view with a table that could be copied and pasted into excel would be grand. Perhaps it would be nice to be able to select the attributes you wanted to change.

If you're short on time, a rake task is the MVP since the practice has been them coming and asking for it and I make them an excel file, and it only happens every six months or so.

**Comment by dfaulken** [comment]
Duplicate for #18, which is more generic.
