### ISSUE TITLE
Invalid Stops Saved in Production

### ISSUE THREAD

**Issue by mboneil10** [umts/stop-project#145]
Running #144 in production fixed one of the 29 stops that had a `shelter_type` of `Modern`. The other 28 stops are `invalid`, so the rake task didn't change their `shelter_types`. All of them are from Monday, June 25 2018. In addition, they're all marked as `completed`, but don't have the fields necessary for that to be true. What should we do with these stops? I'll provide the `hastus_id` and `name` lists below

**Comment by mboneil10** [comment]
Looks like UMTs and SATco

**Comment by mboneil10** [comment]
```
BusStop.all.select(&:invalid?).pluck(:completed).uniq
=> [true]
```

**Comment by dfaulken** [comment]
It's not clear where this left off. Since (as far as I'm aware), an export from this app and import into HASTUS has yet to be undertaken, a good first step in that process would be to ensure that all stops in the DB are valid at the Rails console.

**Comment by dfaulken** [comment]
My mistake - a comment in #138 mentions that an import was performed.
