### ISSUE TITLE
Full list of attributes

### ISSUE THREAD

**Issue by dfaulken** [umts/stop-project#2]
Combining the list of `BusStop` attributes from Hastus and from the current work order sheet the PVTA service crews are using, we have mostly options, a few booleans, and two number fields:

+ Accessible
  + When necessary
  + Not recommended
+ Shelter
  + PVTA
  + Other
  + Building
+ Sign
  + Flag stop
  + Missing sign
  + Needs attention
+ Mounting
  + PVTA pole
  + Other pole
  + Structure
+ Mounting direction
  + Towards street
  + Away from street
+ Bench
  + PVTA
  + Other
+ Trash
  + PVTA
  + Municipal
  + Other
+ Schedule holder
  + On pole
  + In shelter
+ Lighting
  + within 50"
  + 50" - 20'
  + none
+ Curb cut
  + within 20'
  + no curb cut
  + no curb
+ Sidewalk
  + more than 36" wide
  + less than 36" wide
  + none

Booleans:
+ System map exists?
+ Solar lighting?
+ Bus pull out exists?
+ Has power?
+ Straighten pole?
+ Extend pole?
+ New pole?
+ New anchor?
+ Bolt on base?

Number fields:
+ Mounting clearance before
+ Mounting clearance after

I don't know what ~~some~~ most of these mean, let alone how they're used, so for now the plan is to blindly copy them from the forms @sherson shared with me to the interface and then make changes as they're requested without worrying too much about why.

**Comment by sherson** [comment]
Well, when you write it that way ("blindly copy"), it sure seems like a dumb plan 😄 

But yes that list looks OK. We'll get it finalized before we do an import.

**Comment by dfaulken** [comment]
@sherson okayed the final product.

**Comment by werebus** [comment]
>  We'll get it finalized before we do an import

@sherson, any further input here as I'm working on the export?

**Comment by sherson** [comment]
>> We'll get it finalized before we do an import

>  any further input here as I'm working on the export?

I emailed PVTA about this (as well as getting updated oig/d documentation).
