### ISSUE TITLE
Date of stop survey

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#20]
We track when a stop was edited, but we should also probably track when it was actually physically checked/inventoried, and by whom. Related to #18.

**Comment by dfaulken** [comment]
Should this be done automatically, or by manual user input (perhaps a separate model who tracks what stops were surveyed when, with a text field where users can indicate what person/group/entity/agency surveyed it)?

**Comment by sherson** [comment]
All good questions. I'd like to talk with the other garages and PVTA first to get their thoughts.

**Comment by mboneil10** [comment]
During the PVTA meeting on May 31st, it was requested that a user should be able to verify they physically checked/inventoried a stop. @sherson and I decided a button is best.

**Comment by dfaulken** [comment]
A button that does what? Will there be a separate timestamp for it? Will we track who pressed it?

**Comment by sherson** [comment]
>A button that does what? Will there be a separate timestamp for it? Will we track who pressed it?

It will track who pressed it and when.

**Comment by mboneil10** [comment]
Do we think this should be on the edit page or on the manage stops page? Or both?

**Comment by mboneil10** [comment]
After a meeting on June 5, we're going back to the idea of figuring out when the check box is checked. So, using paper trail if we can.

**Comment by sherson** [comment]
I was thinking it should be on the edit page

**Comment by sherson** [comment]
I was asked about this. To clarify, we should track both when it was last checked, and by whom (not be confused with when a stop was modified on a computer days / weeks / months later). That will come in handy for PVTA during the inventory process, and possibly years later.
