### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by dfaulken** [umts/stop-project#21]
Didn't write tests for this. Wasn't necessary for MVP in the agile cycle.

Should backfill them continually.

**Comment by dfaulken** [comment]
Or, could wait until initial set of meetings about this project codifies the desired functionality to the point where writing tests won't be a waste.

**Comment by mboneil10** [comment]
I'll get started on integration tests.

**Comment by mboneil10** [comment]
Here's the plan, 3 different PRS:
- test setup
- unit tests
- system tests

**Comment by mboneil10** [comment]
We're pretty good with tests. I expect coverage to bump once we go deeper into the rewrite.
