### ISSUE TITLE
CSV export - includes only one page (10 stops) of data, and doesn't include routes

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#26]
https://stop-project.admin.umass.edu/bus_stops/manage.csv

Related to #24

**Comment by sherson** [comment]
I exported today and got:


Id | Name | Hastus | Accessible | Bench | Curb cut | Lighting | Mounting | Mounting direction | Schedule holder | Shelter | Sidewalk | Sign | Trash | Bolt on base | Bus pull out exists | Extend pole | Has power | New anchor | New pole | Solar lighting | Straighten pole | System map exists | Mounting clearance after | Mounting clearance before | Created at | Updated at | Completed | Completed at | Sign type | Shelter condition | Shelter pad condition | Shelter pad material | Shelter type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | (Flag stop - signal driver) | 5070 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | FALSE |   | FALSE |   |   | 7/19/16 20:00 | 7/19/16 20:00 |   |   |   |   |   |   |  
3 | 1 Stop Plaza | 1546 |   |   | Within 20' | Within 20' | Other pole |   |   |   | More than 36" |   |   |   |   |   |   |   | FALSE |   | FALSE |   |   | 7/19/16 20:00 | 7/19/16 20:00 |   |   |   |   |   |   |  
5 | 100 Wasson Ave | 9202 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 7/19/16 20:00 | 7/19/16 20:00 |   |   |   |   |   |   |  
7 | 193/188 Mian St (Flag stop - signal driver) | 5048 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | FALSE |   | FALSE |   |   | 7/19/16 20:00 | 7/19/16 20:00 |   |   |   |   |   |   |  
9 | 2133 or 2110 Boston Rd (Flag stop - signal driver) | 5023 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | FALSE |   | FALSE |   |   | 7/19/16 20:00 | 7/19/16 20:00 |   |   |   |   |   |   |  
11 | 2443 or 2440 Boston Rd (Flag stop - signal driver) | 5025 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | FALSE |   | FALSE |   |   | 7/19/16 20:00 | 7/19/16 20:00 |   |   |   |   |   |   |  
13 | 3300 Main Street | 1007 |   |   | No curb cut | Within 20' | PVTA pole |   | On pole |   | More than 36" |   |   |   |   |   |   |   | FALSE |   | FALSE |   |   | 7/19/16 20:00 | 7/19/16 20:00 |   |   |   |   |   |   |  
15 | 333 Western Ave | 937 |   | PVTA |   | Within 20' |   |   | In shelter | PVTA | More than 36" | Missing sign |   |   |   |   |   |   | FALSE |   | FALSE |   |   | 7/19/16 20:00 | 7/19/16 20:00 |   |   |   |   |   |   |  
17 | 3350 Main St | 994 |   |   | No curb cut | Within 20' | PVTA pole |   |   |   | More than 36" |   |   |   |   |   |   |   | FALSE |   | FALSE |   |   | 7/19/16 20:00 | 7/19/16 20:00 |   |   |   |   |   |   |  
19 | 3550 Main St | 967 |   |   | Within 20' | Within 20' | PVTA pole |   |   |   | More than 36" |   |   |   |   |   |   |   | FALSE |   | FALSE |   |   | 7/19/16 20:00 | 7/19/16 20:00 |   |   |   |   |   |   |

**Comment by werebus** [comment]
Just need to not do this for `format.csv`: 

https://github.com/umts/stop-project/pull/24/files#diff-854f0956ae531fb99c98b2797bb578aeR43

**Comment by werebus** [comment]
Probably also the "outdated" export is paginated.

**Comment by mboneil10** [comment]
Confirmed, "outdated" export is paginated as well.

I agree that we can't format the csv in the same way, but we still need to paginate for displaying the stops on the manage page. I could get this done with two different instance variables.
