### ISSUE TITLE
Status of Pending for Stops

### ISSUE THREAD

**Issue by mboneil10** [umts/stop-project#29]
Requested during PVTA meeting on April 30th, 2018:

Show that an incomplete stop is pending after someone started servicing it.

**Comment by dfaulken** [comment]
What's the logic for this one? `updated_at > created_at`? Another timestamp for `imported_at` that we need to add going forward?

**Comment by dfaulken** [comment]
@sherson says:

1. We should reset `created_at` at import. Currently, we effectively do this in that we delete everything ever. We may wish to adopt a less destructive import method.
2. `updated_at > created_at && !completed?` will then be sufficient.

**Comment by sherson** [comment]
PVTA, UMTS, and PVPC are all fine with `updated_at > created_at && !completed?` for pending.

Also, the pending stops should stay in the list of !completed stops, but they should be noted as pending.

**Comment by sherson** [comment]
#34
