### ISSUE TITLE
Fix Page View on Smaller Screen

### ISSUE THREAD

**Issue by mboneil10** [umts/stop-project#33]
I presume most users will be on a phone or tablet? Not entirely sure. Here is what smaller views can look like:

Navbar
<img width="648" alt="screen shot 2018-05-24 at 2 05 32 pm" src="https://user-images.githubusercontent.com/19267771/40503280-98b373dc-5f5b-11e8-83e7-d477bf6e0a98.png">

Text boxes
<img width="859" alt="screen shot 2018-05-24 at 2 06 16 pm" src="https://user-images.githubusercontent.com/19267771/40503304-a4e01e9e-5f5b-11e8-863c-5d4e0cbaa116.png">

Buttons
<img width="791" alt="screen shot 2018-05-24 at 2 06 46 pm" src="https://user-images.githubusercontent.com/19267771/40503339-bd638c8a-5f5b-11e8-8d20-8c4b924332da.png">

etc.

**Comment by mboneil10** [comment]
All that's left is the navbar. @jforgue did some front-end work on the app over this past week.

**Comment by mboneil10** [comment]
@jforgue, is the navbar still an issue?

**Comment by jforgue** [comment]
Yes, I haven't made any changes to the navbar.
