### ISSUE TITLE
User can change stop Name and Hastus ID

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#41]
We should probably prevent this.

**Comment by dfaulken** [comment]
Agreed. In general users shouldn't modify any of the Hastus-is-the-canonical-source attributes.

**Comment by sherson** [comment]
BTW, I discovered this today while playing with the app. I tested to see what would happen and ended up making a duplicate of GRC (which I then renamed):

* Name: GRCtest
* Hastus ID: 999999999999
