### ISSUE TITLE
Editing User Name to One that's Already Been Taken

### ISSUE THREAD

**Issue by mboneil10** [umts/stop-project#46]
Minor error I found while testing:

Editing a user's name to a name already in the db will correctly display error "Name has already been taken", but the user's name in the page title is momentarily changed. Not much of a problem since the page title displays correctly after editing the user again from the users table. 

![edit-user-2](https://user-images.githubusercontent.com/19267771/40948552-04ec83f2-6837-11e8-984b-ec0c5b711363.gif)

**Comment by dfaulken** [comment]
Nice find.

I see two possible solutions:

1. Look the name up from the DB every time (`User.find(@user.id).name`)
2. Just have the title say "Editing User".

**Comment by dfaulken** [comment]
BTW, this `Editing #{thing.name}` pattern is something I've done in a bunch of places, so it may be worth investigating whether this bug exists on any other UMTS projects.

**Comment by mboneil10** [comment]
I think I prefer to go with looking the name up from the DB every time.

If someone were to step away from this and come back to the page later, the wrong name in the user's name field might throw them off. They don't have a way of checking which user they're editing unless they go back to the manage users page. I'm probably bikeshedding at this point, but just wanted to provide my reasoning.

**Comment by mboneil10** [comment]
But... I tried `User.find(@user.id).name` and it changed :(

**Comment by mboneil10** [comment]
UGH easiest fix would be to change the title to user. I'll think on this one.
