### ISSUE TITLE
Stops by Route Page update

### ISSUE THREAD

**Issue by mboneil10** [umts/stop-project#53]
During the meeting on May 31st, changes were requested to the stops by route page:

reformat list items to be Sequence Name (Stop Number)
side note: sequence needs to be added first
order by sequence instead of lexicographically

**Comment by sherson** [comment]
To clarify, it's

`Sequence` / `Name` / `(Stop Number)`

**Comment by sherson** [comment]
Also, we should include Pending at the end if the stop is pending

https://github.com/umts/stop-project/issues/29#issuecomment-397729321

**Comment by mboneil10** [comment]
Closed by #77, #80, and #81
