### ISSUE TITLE
Save Stop - Option to remember route

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#67]
Feature request from Leigh:

The workflow for the users is typically to:

1. Select a route
2. Pick a stop from that route list
3. Mark as completed and hit Save

Currently, that sends the user back to the select stop screen, from which they need to reselect the route. It would be convenient if the user could go back to the route they'd previously selected.

This could be accomplished in various ways. Leigh's first choice is to have a button that goes to the next incomplete stop on the route previously selected. Another option is to have a button that simply goes back to the previous page, or a button that saves without changing pages (and the user can simply tap the browser's back button).

Not high priority.

**Comment by dfaulken** [comment]
> Leigh's first choice is to have a button that goes to the next incomplete stop on the route previously selected.

This probably only makes sense if we implement stop sequence number.

**Comment by dfaulken** [comment]
I would say, short term, store the last selected route in the session, and send people back there if we can. Long term, go by stop sequence number.

**Comment by jforgue** [comment]
How do we know if the users are following the route North or South?

**Comment by sherson** [comment]
Most stops (almost all for UMTS) only exist on one direction per route. However, there are some exceptions (for some routes) such as Haigis Mall, Amherst College, and Hampshire College.
