### ISSUE TITLE
Replace check boxes with select fields/radio buttons

### ISSUE THREAD

**Issue by jforgue** [umts/stop-project#68]
It's been requested that these yes/no questions have a blank default so we can verify that the user has checked the field before completing the form.

**Comment by sherson** [comment]
Right, radio buttons have a slight UI advantage (one tap instead of two), but either approach is fine.

**Comment by jforgue** [comment]
@dfaulken My thoughts exactly. My understanding is that we want this issue solved for Wednesday. Considering that, if I were working on this issue I would go for select fields and move on to something more pressing.

**Comment by sherson** [comment]
UMTS Service confirmed that the checkboxes for any fields for any stops that they marked as complete were updated. That is to say, for stops that UMTS marked as complete since 6/11/2018, anything that is unchecked is assumed to be `No` (while for stops that UMTS did not mark as complete since 6/11, unchecked is assumed to be blank).

**Comment by sherson** [comment]
UMTS Service is not using the app again until Wednesday, so these changes can be made anytime today or tomorrow.

**Comment by mboneil10** [comment]
I'm impartial to this. Radio buttons seem like the way to do this because then we still see that they are bools. I guess a user wouldn't care about that, though.

**Comment by mboneil10** [comment]
And I think the UI advantage is enough for me to make them radio buttons.

**Comment by dfaulken** [comment]
So how about the converse? Should all select fields be displayed as radio buttons? That way all options are readily available in front of you?

**Comment by mboneil10** [comment]
Hm.

**Comment by mboneil10** [comment]
@dfaulken are you playing devil's advocate? Dammit. I don't know what to do.

**Comment by mboneil10** [comment]
Okay, idea is to try out both views: 1) all as select boxes, 2) some as select boxes, some as radio buttons. Then go from there.

**Comment by jforgue** [comment]
Closed with #72.
