### ISSUE TITLE
Modify rake tasks for stops import from Hastus

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#71]
https://github.com/umts/stop-project/tree/master/lib/tasks 

Newest version of stops with routes:
https://umass.box.com/s/q8xfvpusdaoei3hpsp60xtjg6reo9meo 

Newest version of stops for stop project:
https://umass.box.com/s/midj9ghefi2yd64m7un7qgyl448nh3vh

**Comment by sherson** [comment]
UMTS Service is not using the app again until Wednesday, 6/20. So we can save the existing data (to preserve what they've completed since Tuesday, 6/11) anytime today or tomorrow.

**Comment by Anbranin** [comment]
Deadline has been moved to Monday the 25th
