### ISSUE TITLE
Change Columns

### ISSUE THREAD

**Issue by mboneil10** [umts/stop-project#93]
| column            | current type | change to   |
|-------------------|---------------|---------|
| trash             | string        | boolean |
| has_power         | boolean       | string  |
| shared_sign_post  | string        | boolean |
| system_map_exists | boolean       | string  |

**Comment by mboneil10** [comment]
part 2 of 3 for existing data

**Comment by mboneil10** [comment]
Dammit dave. Yes.

**Comment by mboneil10** [comment]
I thought we would be making actual changes _after_ we deploy. I was under the impression that the deploy would only include https://github.com/umts/stop-project/issues/89, though.

**Comment by sherson** [comment]
Shared Sign Post needs to be renamed to `Shared sign post FRTA` as per field guide.
