### ISSUE TITLE
Exclude non-public routes and stops from Hastus import

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#98]
https://github.com/umts/stop-project/tree/master/contrib

#97 (only loosely related)

**Comment by mboneil10** [comment]
uhhh

**Comment by dfaulken** [comment]
Relevant Hastus columns are `stp_is_public` and `rte_for_public_info`, I believe.

**Comment by dfaulken** [comment]
@mboneil10 done correct? The PRs were merged, but looks like that might not have closed the issue.

**Comment by mboneil10** [comment]
Yes, thanks for going through these.
